const randomPara = [

  "Morning light filtered through the trees, casting dappled shadows on the forest floor. Birds chirped from the canopy above, filling the silence with music. A squirrel darted up a trunk, pausing to watch, then vanished into the leaves. The world felt still, held in that moment of golden peace.",
  "The city never slept. Neon signs buzzed overhead, casting a kaleidoscope of colors onto wet pavement. Taxis honked, people hurried, and street musicians played for change. Amid the chaos, a man stood still, sipping coffee and watching life rush by in a blur of movement and sound.",
  "A storm rolled in across the plains, thunder rumbling like ancient drums. Lightning split the sky, illuminating the tall grasses that danced in the wind. Horses in the distance galloped for shelter, their silhouettes flashing with each electric bolt. The air smelled of ozone and wet earth.",
  "Snow fell gently, blanketing the world in white. Each flake drifted down in silence, erasing footsteps and softening every edge. A child laughed as they caught snowflakes on their tongue, cheeks red with cold. Winter had arrived, and with it, a hush that made even the city hold its breath.",
  "The ocean stretched endlessly, waves rising and falling in an eternal rhythm. Seagulls cried above, riding thermals with ease. On the shore, driftwood collected in tangled piles. A message in a bottle lay half-buried in the sand, its story sealed inside, waiting to be found.",
  "A train whistle echoed through the valley, long and mournful. Steam hissed as wheels clattered over rails, shaking the platform. Travelers clutched their bags, faces anxious or excited. The engine gleamed in the morning light, promising distant cities, new beginnings, and endless stories.",
  "He opened the journal carefully, as if it might crumble. Each page was filled with looping script, tiny sketches, and pressed flowers. It had belonged to his grandmother, a woman he barely knew. Now, through her words, she lived again, her thoughts reaching across decades to meet his own.",
  "In the attic, dust hung in the air like mist. Boxes were stacked to the ceiling, filled with forgotten memories. A trunk sat in the corner, locked but not hidden. He knelt, turning the key he’d found in an old drawer. The lid creaked open, revealing photographs, letters, and a single gold ring.",
  "The desert stretched out in every direction, vast and unforgiving. Heat shimmered above the sand, distorting the horizon. Cacti stood like sentinels, their spines sharp and gleaming. A lone traveler trudged forward, eyes fixed on the next dune, each step a victory against the sun.",
  "Lanterns floated into the night sky, glowing like fireflies. Each carried a wish, scribbled in careful handwriting. Families and lovers watched them rise, hands clasped in hope. The river below reflected the lights, doubling the stars. For one night, magic felt real, and anything seemed possible.",
  "The café buzzed with soft conversation and the clink of porcelain. A barista sang quietly as they worked the espresso machine. Outside, rain tapped gently on the window, turning the world gray. Inside, the smell of coffee and the warmth of shared silence wrapped everyone in comfort.",
  "A violin’s notes floated from an open window, haunting and sweet. Passersby slowed, caught by the melody. The player sat alone, eyes closed, lost in the music. In that moment, the street changed—becoming a stage, the city an audience. Even pigeons seemed to pause, mesmerized by the sound.",
  "He stood at the edge of the cliff, wind tugging at his coat. Below, waves crashed violently against jagged rocks. His thoughts churned like the sea—memories of choices made, words left unsaid. But the sky was clear, and in the distance, a lighthouse blinked. There was always a way forward.",
  "The garden was wild, vines twisting over stone walls, flowers blooming in riotous color. Bees hummed from bloom to bloom, and butterflies danced in the sunlight. She moved through it slowly, fingers brushing petals, the scent of lavender and roses clinging to her dress and skin.",
  "The courtroom fell silent as the final verdict was read. The defendant’s hands trembled, eyes locked on the floor. Behind them, a mother wept softly. Justice, some said. Others whispered injustice. But in that room, truth felt fragile, balanced on the edge of every breath held.",
  "The spaceship hovered above the alien planet, engines quiet. Through the glass, the landscape shimmered—blue plants, tall crystal spires, skies with two suns. The crew watched in awe, their mission finally real. For the first time, humanity had stepped beyond the stars into the unknown.",
  "A fire crackled in the hearth, casting flickering light on stone walls. Outside, the wind howled across the moors, rattling shutters. Inside, stories were told—of ghosts, of heroes, of lost loves. The night stretched on, and in that old inn, time seemed to pause and listen.",
  "The clock ticked louder in the silence of the room. She sat by the window, watching leaves fall. Each drop of golden foliage reminded her of years gone by, of laughter and tears. Her tea had gone cold, but she didn’t notice. Her mind wandered down paths no longer walked, memories unfolding.",
  "The festival roared to life as night fell. Drums thundered, lights flashed, and crowds danced in the streets. Masks hid smiles and eyes sparkled with mischief. Somewhere, a fire juggler spun flame into the air, drawing gasps. For one night, rules vanished and joy became the law of the land.",
  "Time passed differently in the mountains. Clouds drifted slow and low, clinging to peaks. Waterfalls carved the rock with patient force. She hiked in silence, breath visible in the cold. With every step, worries from the world below faded, replaced by the rhythm of her boots and the wind.",
];

export default randomPara